### ISSUE TITLE
Javascript linkt nergens naartoe

### ISSUE THREAD

**Issue by CathelijneVisser** [Metehan2003/your-tribe-squad-page#1]
https://github.com/DamianR2004/your-tribe-squad-page/blob/74fdc129132661598f4a5253661a6594a926eb6a/index.html#L14

Ik denk dat jullie naar het bestandje javabook.js willen linken maar deze linkt naar main.js maar dat bestandje bestaat niet.

**Comment by Metehan2003** [comment]
Link is weggehaald.
